### ISSUE TITLE
Recommender system unable to fetch current user from db

### ISSUE THREAD

**Issue by edvardvb** [askbk/inmarket-backend#13]
https://github.com/askbk/inmarket-backend/blob/development/src/components/recommendation/recommendationController.js#L49

This request to the DB was unable to return the user object for user with id 1.  

![image](https://user-images.githubusercontent.com/8725291/58008129-066a2180-7aec-11e9-9da7-c265b090857c.png)

**Comment by askbk** [comment]
This is because users 1 and 2 are test users that aren't associated with any records in neither the Jobseekers table nor the Employees table.

This error will also occur if you try to fetch recommendations for users 3 and 4 (if using the provided test data), as these are registered as companies.

Will add user 1 and 2 to jobseekers/employees and add a check to make sure the id exists.
